# Site settings
title:         Lazyer 
description:    "LazyerIJ Blog"
url:            "https://LazyerIJ.github.io"

# Google Analytics
google_analytics: G-S9J9538CWE


# Author
author:
  name:         Lazyer IJ
  url:          https://LazyerIJ.github.io
  email:        spozam01@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
